### ISSUE TITLE
Add a "reverse dependencies" example

### ISSUE THREAD

**Issue by dolmen** [CPAN-API/metacpan-explorer#9]
"Which are the reverse dependencies of dist X?" is a common query I would like to learn to build.
It would be helpful to have it as an example.

**Comment by oalders** [comment]
https://github.com/CPAN-API/metacpan-examples/tree/master/scripts/endpoints/search/reverse_dependencies

**Comment by dolmen** [comment]
Very useful link!

Anyway, this request is for the metacpan-explorer UI.

**Comment by rwstauner** [comment]
There is a link in the sidebar for "Distributions that depend on MetaCPAN::API"...
is that different than what you're asking for?

**Comment by dolmen** [comment]
@rwstauner No! This is exactly what I asked. Sorry for the noise.

**Comment by rwstauner** [comment]
No problem.
If you have a suggestion for how to make that more apparent, please do.

**Comment by dolmen** [comment]
Two suggestions:
- using MetaCPAN::API in the example is confusing (as the explorer already speaks about MetaCPAN and API everywhere). It would be more clear to use a well known distribution. For example, Module::Build, List::MoreUtils...
- I'm now familiar with the term "reverse dependencies" that I see on MetaCPAN.org, and that's what I expected to see

**Comment by rwstauner** [comment]
Yeah, I thought the same thing about the module name, but i clicked it
because I knew what i was looking for.
We should pick something else as an example.
